name: Build Wheels
permissions:
  contents: read

on:
  push:
      branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: 'Wheel: ${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}'
    strategy:
      fail-fast: false
      matrix:
        python: [cp312, cp314t, cp315t]
        platform:
          - { os: ubuntu-latest,     arch: x86_64,     cibw_system: manylinux }
          - { os: ubuntu-24.04-arm,  arch: aarch64,    cibw_system: manylinux }
          - { os: ubuntu-latest,     arch: x86_64,     cibw_system: musllinux }
          - { os: ubuntu-24.04-arm,  arch: aarch64,    cibw_system: musllinux }
          - { os: macos-latest,      arch: arm64,      cibw_system: macosx }
          - { os: windows-latest,    arch: AMD64,      cibw_system: win }
          # - { os: macos-13,          arch: x86_64,     cibw_system: macosx }
    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Install Astral UV
        uses: astral-sh/setup-uv@v10.0.0
        with:
          enable-cache: true
          cache-suffix: -${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}

      - name: Build and test wheels
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_TEST_COMMAND: pytest {project}/tests --import-mode=importlib --ignore={project}/tests/experimental --ignore={project}/tests/downstream --ignore={project}/tests/comparison --ignore={project}/tests/benchmarks -v -n auto --cov=bareduckdb --cov-report=term-missing
          CIBW_TEST_EXTRAS: "test"
          CIBW_TEST_REQUIRES: filelock
          CIBW_ARCHS: ${{ matrix.platform.arch }}
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}

      - name: Upload wheel
        uses: actions/upload-artifact@v7.0.1
        with:
          name: wheel-${{ matrix.python }}-${{ matrix.platform.cibw_system }}_${{ matrix.platform.arch }}
          path: wheelhouse/*.whl
          compression-level: 0

  publish-wheels:
    name: Publish Wheels to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: wheel-*
          merge-multiple: true

      - name: List wheels
        run: |
          ls -lh dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
